export const disabilityOptions = [
  {
    value: "ADHD (Attention Deficit Hyperactivity Disorder)",
    label: "ADHD (Attention Deficit Hyperactivity Disorder)",
  },
  { value: "Amputation", label: "Amputation" },
  { value: "Anxiety Disorder", label: "Anxiety Disorder" },
  { value: "Arthritis", label: "Arthritis" },
  {
    value: "Autism Spectrum Disorder (ASD)",
    label: "Autism Spectrum Disorder (ASD)",
  },
  {
    value: "Autoimmune Disorders affecting mobility or cognition",
    label: "Autoimmune Disorders affecting mobility or cognition",
  },
  { value: "Bipolar Disorder", label: "Bipolar Disorder" },
  { value: "Blindness", label: "Blindness" },
  { value: "Cerebral Palsy", label: "Cerebral Palsy" },
  {
    value: "Chronic Fatigue Syndrome (CFS)",
    label: "Chronic Fatigue Syndrome (CFS)",
  },
  { value: "Chronic Pain", label: "Chronic Pain" },
  { value: "Deafblindness", label: "Deafblindness" },
  { value: "Deafness", label: "Deafness" },
  { value: "Depression", label: "Depression" },
  {
    value: "Diabetes-related Disability",
    label: "Diabetes-related Disability",
  },
  { value: "Down Syndrome", label: "Down Syndrome" },
  { value: "Dyslexia", label: "Dyslexia" },
  { value: "Dyspraxia", label: "Dyspraxia" },
  { value: "Epilepsy", label: "Epilepsy" },
  { value: "Fibromyalgia", label: "Fibromyalgia" },
  { value: "Hearing Impairment", label: "Hearing Impairment" },
  { value: "Intellectual Disability", label: "Intellectual Disability" },
  {
    value: "Learning Disability (Dyslexia, Dyscalculia, Dysgraphia)",
    label: "Learning Disability (Dyslexia, Dyscalculia, Dysgraphia)",
  },
  { value: "Lupus", label: "Lupus" },
  { value: "Mobility Impairment", label: "Mobility Impairment" },
  { value: "Multiple Sclerosis", label: "Multiple Sclerosis" },
  { value: "Muscular Dystrophy", label: "Muscular Dystrophy" },
  {
    value: "Nonverbal Communication Disabilities",
    label: "Nonverbal Communication Disabilities",
  },
  {
    value: "Obsessive-Compulsive Disorder (OCD)",
    label: "Obsessive-Compulsive Disorder (OCD)",
  },
  {
    value: "Post-Traumatic Stress Disorder (PTSD)",
    label: "Post-Traumatic Stress Disorder (PTSD)",
  },
  { value: "Rare Genetic Disorders", label: "Rare Genetic Disorders" },
  { value: "Schizophrenia", label: "Schizophrenia" },
  {
    value: "Speech Impairment (Stuttering, Apraxia)",
    label: "Speech Impairment (Stuttering, Apraxia)",
  },
  { value: "Spinal Cord Injury", label: "Spinal Cord Injury" },
  { value: "Stroke-related Disability", label: "Stroke-related Disability" },
  { value: "Tourette Syndrome", label: "Tourette Syndrome" },
  {
    value: "Traumatic Brain Injury (TBI)",
    label: "Traumatic Brain Injury (TBI)",
  },
  { value: "Visual Impairment", label: "Visual Impairment" },
];

export const languageOptions = [
  { value: "ENGLISH", label: "English" },
  { value: "FILIPINO", label: "Filipino" },
  { value: "CEBUANO", label: "Cebuano" },
  { value: "ILOCANO", label: "Ilocano" },
  { value: "HILIGAYNON", label: "Hiligaynon" },
  { value: "WARAY", label: "Waray" },
  { value: "KAPAMPANGAN", label: "Kapampangan" },
  { value: "PANGASINAN", label: "Pangasinan" },
  { value: "BICOLANO", label: "Bicolano" },
  { value: "MARANAO", label: "Maranao" },
  { value: "MAGUINDANAO", label: "Maguindanao" },
  { value: "TAUSUG", label: "Tausug" },
  { value: "CHAVACANO", label: "Chavacano" },
  { value: "AKLANON", label: "Aklanon" },
  { value: "KANKANAEY", label: "Kankanaey" },
  { value: "IFUGAO", label: "Ifugao" },
  { value: "IVATAN", label: "Ivatan" },
];

export const jobCategoryOptions = [
  { value: "DESIGN", label: "Design" },
  { value: "DEVELOPMENT", label: "Development" },
  { value: "MARKETING", label: "Marketing" },
  { value: "SALES", label: "Sales" },
  { value: "ENGINEERING", label: "Engineering" },
  { value: "HR", label: "HR" },
  { value: "FINANCE", label: "Finance" },
  { value: "MANAGEMENT", label: "Management" },
  { value: "PRODUCT", label: "Product" },
  { value: "CUSTOMER_SUPPORT", label: "Customer Support" },
  { value: "OPERATIONS", label: "Operations" },
  { value: "RESEARCH", label: "Research" },
  { value: "EDUCATION", label: "Education" },
  { value: "ADMINISTRATION", label: "Administration" },
  { value: "IT", label: "IT" },
  { value: "CONSULTING", label: "Consulting" },
  { value: "HEALTHCARE", label: "Healthcare" },
  { value: "CONSTRUCTION", label: "Construction" },
  { value: "LEGAL", label: "Legal" },
  { value: "ART", label: "Art" },
  { value: "MEDIA", label: "Media" },
];

export const jobTypeOptions = [
  { value: "Full-Time", label: "Full-Time" },
  { value: "Part-Time", label: "Part-Time" },
  { value: "Freelance", label: "Freelance" },
  { value: "Contract", label: "Contract" },
  { value: "Internship", label: "Internship" },
];

export const jobShiftOptions = [
  { value: "Part-Time", label: "Part-Time" },
  { value: "Full-Time", label: "Full-Time" },
  { value: "Fixed", label: "Fixed" },
  { value: "Night-Shift", label: "Night-Shift" },
  { value: "Day-Shift", label: "Day-Shift" },
];

export const jobQualificationsOptions = [
  { value: "Bachelor's Degree", label: "Bachelor's Degree" },
  { value: "High School Diploma", label: "High School Diploma" },
  { value: "Technical Training", label: "Technical Training" },
  { value: "College Undergraduate", label: "College Undergraduate" },
  { value: "Master's Degree", label: "Master's Degree" },
  { value: "Doctorate Degree", label: "Doctorate Degree" },
];

export const jobLevelOptions = [
  { value: "Entry", label: "Entry" },
  { value: "Mid", label: "Mid-Level" },
  { value: "Senior", label: "Senior" },
  { value: "Manager", label: "Manager" },
  { value: "Officer", label: "Officer" },
  { value: "Student", label: "Student" },
];

export const locationOptions = [
  { label: "Pangasinan, Alaminos City", value: "Pangasinan, Alaminos City" },
  { label: "Pangasinan, Dagupan City", value: "Pangasinan, Dagupan City" },
  {
    label: "Pangasinan, San Carlos City",
    value: "Pangasinan, San Carlos City",
  },
  { label: "Pangasinan, Urdaneta City", value: "Pangasinan, Urdaneta City" },

  { label: "Pangasinan, Lingayen", value: "Pangasinan, Lingayen" },
  { label: "Pangasinan, Calasiao", value: "Pangasinan, Calasiao" },
  { label: "Pangasinan, Binmaley", value: "Pangasinan, Binmaley" },
  { label: "Pangasinan, Mangaldan", value: "Pangasinan, Mangaldan" },
  { label: "Pangasinan, Bayambang", value: "Pangasinan, Bayambang" },
  { label: "Pangasinan, Malasiqui", value: "Pangasinan, Malasiqui" },
  { label: "Pangasinan, Manaoag", value: "Pangasinan, Manaoag" },
  { label: "Pangasinan, Rosales", value: "Pangasinan, Rosales" },
  { label: "Pangasinan, San Fabian", value: "Pangasinan, San Fabian" },
  { label: "Pangasinan, Tayug", value: "Pangasinan, Tayug" },
  { label: "Pangasinan, Sual", value: "Pangasinan, Sual" },
  { label: "Pangasinan, Bolinao", value: "Pangasinan, Bolinao" },
  { label: "Pangasinan, Pozorrubio", value: "Pangasinan, Pozorrubio" },

  { label: "Metro Manila, Caloocan", value: "Metro Manila, Caloocan" },
  { label: "Metro Manila, Las Piñas", value: "Metro Manila, Las Piñas" },
  { label: "Metro Manila, Makati", value: "Metro Manila, Makati" },
  { label: "Metro Manila, Malabon", value: "Metro Manila, Malabon" },
  { label: "Metro Manila, Mandaluyong", value: "Metro Manila, Mandaluyong" },
  { label: "Metro Manila, Manila", value: "Metro Manila, Manila" },
  { label: "Metro Manila, Marikina", value: "Metro Manila, Marikina" },
  { label: "Metro Manila, Muntinlupa", value: "Metro Manila, Muntinlupa" },
  { label: "Metro Manila, Navotas", value: "Metro Manila, Navotas" },
  { label: "Metro Manila, Parañaque", value: "Metro Manila, Parañaque" },
  { label: "Metro Manila, Pasay", value: "Metro Manila, Pasay" },
  { label: "Metro Manila, Pasig", value: "Metro Manila, Pasig" },
  { label: "Metro Manila, Quezon City", value: "Metro Manila, Quezon City" },
  { label: "Metro Manila, San Juan", value: "Metro Manila, San Juan" },
  { label: "Metro Manila, Taguig", value: "Metro Manila, Taguig" },
  { label: "Metro Manila, Valenzuela", value: "Metro Manila, Valenzuela" },

  { label: "Ilocos Norte, Laoag", value: "Ilocos Norte, Laoag" },
  { label: "Ilocos Sur, Vigan", value: "Ilocos Sur, Vigan" },
  { label: "La Union, San Fernando", value: "La Union, San Fernando" },

  { label: "Batanes, Basco", value: "Batanes, Basco" },
  { label: "Cagayan, Tuguegarao", value: "Cagayan, Tuguegarao" },
  { label: "Isabela, Ilagan", value: "Isabela, Ilagan" },
  { label: "Isabela, Cauayan", value: "Isabela, Cauayan" },
  { label: "Isabela, Santiago", value: "Isabela, Santiago" },
  { label: "Nueva Vizcaya, Bayombong", value: "Nueva Vizcaya, Bayombong" },
  { label: "Quirino, Cabarroguis", value: "Quirino, Cabarroguis" },

  { label: "Aurora, Baler", value: "Aurora, Baler" },
  { label: "Bataan, Balanga", value: "Bataan, Balanga" },
  { label: "Bulacan, Malolos", value: "Bulacan, Malolos" },
  { label: "Bulacan, Meycauayan", value: "Bulacan, Meycauayan" },
  {
    label: "Bulacan, San Jose del Monte",
    value: "Bulacan, San Jose del Monte",
  },
  { label: "Nueva Ecija, Palayan", value: "Nueva Ecija, Palayan" },
  { label: "Nueva Ecija, Cabanatuan", value: "Nueva Ecija, Cabanatuan" },
  { label: "Nueva Ecija, Gapan", value: "Nueva Ecija, Gapan" },
  { label: "Pampanga, San Fernando", value: "Pampanga, San Fernando" },
  { label: "Tarlac, Tarlac City", value: "Tarlac, Tarlac City" },
  { label: "Zambales, Iba", value: "Zambales, Iba" },
  { label: "Zambales, Olongapo", value: "Zambales, Olongapo" },

  { label: "Batangas, Batangas City", value: "Batangas, Batangas City" },
  { label: "Batangas, Lipa", value: "Batangas, Lipa" },
  { label: "Batangas, Tanauan", value: "Batangas, Tanauan" },
  { label: "Cavite, Trece Martires", value: "Cavite, Trece Martires" },
  { label: "Cavite, Bacoor", value: "Cavite, Bacoor" },
  { label: "Cavite, Cavite City", value: "Cavite, Cavite City" },
  { label: "Cavite, Dasmariñas", value: "Cavite, Dasmariñas" },
  { label: "Cavite, Imus", value: "Cavite, Imus" },
  { label: "Cavite, Tagaytay", value: "Cavite, Tagaytay" },
  { label: "Cavite, General Trias", value: "Cavite, General Trias" },
  { label: "Laguna, Santa Cruz", value: "Laguna, Santa Cruz" },
  { label: "Laguna, Biñan", value: "Laguna, Biñan" },
  { label: "Laguna, Cabuyao", value: "Laguna, Cabuyao" },
  { label: "Laguna, Calamba", value: "Laguna, Calamba" },
  { label: "Laguna, San Pablo", value: "Laguna, San Pablo" },
  { label: "Laguna, Santa Rosa", value: "Laguna, Santa Rosa" },
  { label: "Quezon, Lucena", value: "Quezon, Lucena" },
  { label: "Rizal, Antipolo", value: "Rizal, Antipolo" },

  { label: "Marinduque, Boac", value: "Marinduque, Boac" },
  {
    label: "Occidental Mindoro, Mamburao",
    value: "Occidental Mindoro, Mamburao",
  },
  { label: "Oriental Mindoro, Calapan", value: "Oriental Mindoro, Calapan" },
  { label: "Palawan, Puerto Princesa", value: "Palawan, Puerto Princesa" },
  { label: "Caloocan City", value: "Caloocan City" },
  { label: "Las Piñas City", value: "Las Piñas City" },
  { label: "Makati City", value: "Makati City" },
  { label: "Malabon City", value: "Malabon City" },
  { label: "Mandaluyong City", value: "Mandaluyong City" },
  { label: "Manila City", value: "Manila City" },
  { label: "Marikina City", value: "Marikina City" },
  { label: "Muntinlupa City", value: "Muntinlupa City" },
  { label: "Navotas City", value: "Navotas City" },
  { label: "Parañaque City", value: "Parañaque City" },
  { label: "Pasay City", value: "Pasay City" },
  { label: "Pasig City", value: "Pasig City" },
  { label: "Quezon City", value: "Quezon City" },
  { label: "San Juan City", value: "San Juan City" },
  { label: "Taguig City", value: "Taguig City" },
  { label: "Valenzuela City", value: "Valenzuela City" },

  { label: "Abra, Bangued", value: "Abra, Bangued" },
  {
    label: "Agusan del Norte, Butuan City",
    value: "Agusan del Norte, Butuan City",
  },
  {
    label: "Agusan del Sur, Bayugan City",
    value: "Agusan del Sur, Bayugan City",
  },
  { label: "Aklan, Kalibo", value: "Aklan, Kalibo" },
  { label: "Albay, Legazpi City", value: "Albay, Legazpi City" },
  { label: "Albay, Ligao City", value: "Albay, Ligao City" },
  { label: "Albay, Tabaco City", value: "Albay, Tabaco City" },
  {
    label: "Antique, San Jose de Buenavista",
    value: "Antique, San Jose de Buenavista",
  },
  { label: "Apayao, Kabugao", value: "Apayao, Kabugao" },
  { label: "Aurora, Baler", value: "Aurora, Baler" },
  { label: "Basilan, Isabela City", value: "Basilan, Isabela City" },
  { label: "Basilan, Lamitan City", value: "Basilan, Lamitan City" },
  { label: "Bataan, Balanga City", value: "Bataan, Balanga City" },
  { label: "Batanes, Basco", value: "Batanes, Basco" },
  { label: "Batangas, Batangas City", value: "Batangas, Batangas City" },
  { label: "Batangas, Lipa City", value: "Batangas, Lipa City" },
  { label: "Batangas, Tanauan City", value: "Batangas, Tanauan City" },
  { label: "Benguet, Baguio City", value: "Benguet, Baguio City" },
  { label: "Biliran, Naval", value: "Biliran, Naval" },
  { label: "Bohol, Tagbilaran City", value: "Bohol, Tagbilaran City" },
  { label: "Bukidnon, Malaybalay City", value: "Bukidnon, Malaybalay City" },
  { label: "Bukidnon, Valencia City", value: "Bukidnon, Valencia City" },
  { label: "Bulacan, Malolos City", value: "Bulacan, Malolos City" },
  { label: "Bulacan, Meycauayan City", value: "Bulacan, Meycauayan City" },
  {
    label: "Bulacan, San Jose del Monte City",
    value: "Bulacan, San Jose del Monte City",
  },
  { label: "Cagayan, Tuguegarao City", value: "Cagayan, Tuguegarao City" },
  { label: "Camarines Norte, Daet", value: "Camarines Norte, Daet" },
  { label: "Camarines Sur, Iriga City", value: "Camarines Sur, Iriga City" },
  { label: "Camarines Sur, Naga City", value: "Camarines Sur, Naga City" },
  { label: "Camiguin, Mambajao", value: "Camiguin, Mambajao" },
  { label: "Capiz, Roxas City", value: "Capiz, Roxas City" },
  { label: "Catanduanes, Virac", value: "Catanduanes, Virac" },
  { label: "Cavite, Bacoor City", value: "Cavite, Bacoor City" },
  { label: "Cavite, Cavite City", value: "Cavite, Cavite City" },
  { label: "Cavite, Dasmariñas City", value: "Cavite, Dasmariñas City" },
  { label: "Cavite, General Trias City", value: "Cavite, General Trias City" },
  { label: "Cavite, Imus City", value: "Cavite, Imus City" },
  { label: "Cavite, Tagaytay City", value: "Cavite, Tagaytay City" },
  {
    label: "Cavite, Trece Martires City",
    value: "Cavite, Trece Martires City",
  },
  { label: "Cebu, Bogo City", value: "Cebu, Bogo City" },
  { label: "Cebu, Carcar City", value: "Cebu, Carcar City" },
  { label: "Cebu, Cebu City", value: "Cebu, Cebu City" },
  { label: "Cebu, Danao City", value: "Cebu, Danao City" },
  { label: "Cebu, Lapu-Lapu City", value: "Cebu, Lapu-Lapu City" },
];
