export const disabilityOptions = [
  { value: "Mobility Impairment", label: "Mobility Impairment" },
  { value: "Amputation", label: "Amputation" },
  { value: "Cerebral Palsy", label: "Cerebral Palsy" },
  { value: "Muscular Dystrophy", label: "Muscular Dystrophy" },
  { value: "Spinal Cord Injury", label: "Spinal Cord Injury" },
  { value: "Multiple Sclerosis", label: "Multiple Sclerosis" },
  { value: "Arthritis", label: "Arthritis" },
  { value: "Stroke-related Disability", label: "Stroke-related Disability" },
  { value: "Visual Impairment", label: "Visual Impairment" },
  { value: "Blindness", label: "Blindness" },
  { value: "Hearing Impairment", label: "Hearing Impairment" },
  { value: "Deafness", label: "Deafness" },
  { value: "Deafblindness", label: "Deafblindness" },
  { value: "Down Syndrome", label: "Down Syndrome" },
  { value: "Autism Spectrum Disorder (ASD)", label: "Autism Spectrum Disorder (ASD)" },
  { value: "Intellectual Disability", label: "Intellectual Disability" },
  { value: "Learning Disability (Dyslexia, Dyscalculia, Dysgraphia)", label: "Learning Disability (Dyslexia, Dyscalculia, Dysgraphia)" },
  { value: "ADHD (Attention Deficit Hyperactivity Disorder)", label: "ADHD (Attention Deficit Hyperactivity Disorder)" },
  { value: "Dyslexia", label: "Dyslexia" },
  { value: "Dyspraxia", label: "Dyspraxia" },
  { value: "Tourette Syndrome", label: "Tourette Syndrome" },
  { value: "Anxiety Disorder", label: "Anxiety Disorder" },
  { value: "Depression", label: "Depression" },
  { value: "Bipolar Disorder", label: "Bipolar Disorder" },
  { value: "Schizophrenia", label: "Schizophrenia" },
  { value: "Post-Traumatic Stress Disorder (PTSD)", label: "Post-Traumatic Stress Disorder (PTSD)" },
  { value: "Obsessive-Compulsive Disorder (OCD)", label: "Obsessive-Compulsive Disorder (OCD)" },
  { value: "Epilepsy", label: "Epilepsy" },
  { value: "Chronic Fatigue Syndrome (CFS)", label: "Chronic Fatigue Syndrome (CFS)" },
  { value: "Fibromyalgia", label: "Fibromyalgia" },
  { value: "Lupus", label: "Lupus" },
  { value: "Diabetes-related Disability", label: "Diabetes-related Disability" },
  { value: "Chronic Pain", label: "Chronic Pain" },
  { value: "Speech Impairment (Stuttering, Apraxia)", label: "Speech Impairment (Stuttering, Apraxia)" },
  { value: "Nonverbal Communication Disabilities", label: "Nonverbal Communication Disabilities" },
  { value: "Rare Genetic Disorders", label: "Rare Genetic Disorders" },
  { value: "Autoimmune Disorders affecting mobility or cognition", label: "Autoimmune Disorders affecting mobility or cognition" },
  { value: "Traumatic Brain Injury (TBI)", label: "Traumatic Brain Injury (TBI)" },
];

export const languageOptions = [
  { value: "ENGLISH", label: "English" },
  { value: "FILIPINO", label: "Filipino" },
  { value: "CEBUANO", label: "Cebuano" },
  { value: "ILOCANO", label: "Ilocano" },
  { value: "HILIGAYNON", label: "Hiligaynon" },
  { value: "WARAY", label: "Waray" },
  { value: "KAPAMPANGAN", label: "Kapampangan" },
  { value: "PANGASINAN", label: "Pangasinan" },
  { value: "BICOLANO", label: "Bicolano" },
  { value: "MARANAO", label: "Maranao" },
  { value: "MAGUINDANAO", label: "Maguindanao" },
  { value: "TAUSUG", label: "Tausug" },
  { value: "CHAVACANO", label: "Chavacano" },
  { value: "AKLANON", label: "Aklanon" },
  { value: "KANKANAEY", label: "Kankanaey" },
  { value: "IFUGAO", label: "Ifugao" },
  { value: "IVATAN", label: "Ivatan" }
];
